version: '3.3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  example-one:
    environment:
      VIRTUAL_HOST: example-one.com
    image: nginx:alpine
    volumes:
      - ./example-one/index.html:/usr/share/nginx/html/index.html

  example-two:
    environment:
      VIRTUAL_HOST: example-two.net
    image: nginx:alpine
    volumes:
      - ./example-two/index.html:/usr/share/nginx/html/index.html
